local ls = require 'luasnip'
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets('cpp', {

  -- ==================== CP FULL ====================
  s('cpfull', {
    t {
      '/*',
      'Author: Rahul Samant',
      'Created: ',
    },
    i(1, os.date '%Y-%m-%d %H:%M:%S'),
    t {
      '',
      '*/',
      '',
      '#include <bits/stdc++.h>',
      'using namespace std;',
      '',
      '// ==================== TYPE DEFINITIONS ====================',
      'typedef long long ll;',
      'typedef unsigned long long ull;',
      'typedef long double ld;',
      'typedef pair<int, int> pii;',
      'typedef pair<ll, ll> pll;',
      'typedef vector<int> vi;',
      'typedef vector<ll> vll;',
      'typedef vector<pii> vpii;',
      'typedef vector<pll> vpll;',
      'typedef vector<vi> vvi;',
      'typedef vector<vll> vvll;',
      '',
      '// ==================== MACROS ====================',
      '#define all(x) (x).begin(), (x).end()',
      '#define rall(x) (x).rbegin(), (x).rend()',
      '#define pb push_back',
      '#define eb emplace_back',
      '#define mp make_pair',
      '#define fi first',
      '#define se second',
      '#define sz(x) (int)(x).size()',
      '#define rep(i, a, b) for(int i = (a); i < (b); ++i)',
      '#define per(i, a, b) for(int i = (b) - 1; i >= (a); --i)',
      '#define trav(a, x) for(auto& a : x)',
      "#define endl '\\n'",
      '',
      '// ==================== DEBUG ====================',
      '#ifdef LOCAL',
      '#define DEBUG 1',
      '#else',
      '#define DEBUG 0',
      '#endif',
      '',
      '#define debug(x) if(DEBUG) { cerr << "[DEBUG] " << #x << " = " << (x) << endl; }',
      '',
      'const int MOD = 1e9 + 7;',
      'const ll INF = 1e18;',
      '',
      'void setup_io() {',
      '    ios_base::sync_with_stdio(false);',
      '    cin.tie(nullptr);',
      '    #ifdef LOCAL',
      '    freopen("input.txt", "r", stdin);',
      '    freopen("output.txt", "w", stdout);',
      '    #endif',
      '}',
      '',
      'void solve() {',
      '    ',
    },
    i(0),
    t {
      '',
      '}',
      '',
      'int main() {',
      '    setup_io();',
      '    int t;',
      '    cin >> t;',
      '    while(t--) solve();',
      '    return 0;',
      '}',
    },
  }),

  -- ==================== CP BASIC ====================
  s('cpbasic', {
    t {
      '/*',
      'Author: Rahul Samant',
      'Created: ',
    },
    i(1, os.date '%Y-%m-%d %H:%M:%S'),
    t {
      '',
      '*/',
      '',
      '#include <bits/stdc++.h>',
      'using namespace std;',
      '',
      'typedef long long ll;',
      'typedef vector<int> vi;',
      '',
      '#define all(x) (x).begin(), (x).end()',
      '#define pb push_back',
      '#define rep(i,a,b) for(int i=a;i<b;i++)',
      '',
      'void solve(){',
      '    ',
    },
    i(0),
    t {
      '',
      '}',
      '',
      'int main(){',
      '    ios::sync_with_stdio(false);',
      '    cin.tie(nullptr);',
      '    int t; cin>>t;',
      '    while(t--) solve();',
      '}',
    },
  }),

  -- ==================== BASIC CPP ====================
  s('basiccpp', {
    t {
      '#include <bits/stdc++.h>',
      'using namespace std;',
      '',
      'int main(){',
      '    ',
    },
    i(0),
    t {
      '',
      '    return 0;',
      '}',
    },
  }),
})
